Sonification Workshop-Adrián García Riber-2026

In [1]:
#!pip3 install pandas

In [2]:
import pandas as pd
import numpy as np

In [3]:
# Loading a table.txt as a pandas dataframe
df = pd.read_csv("Bastien-CDS-J-ApJ-788-L9-table1.txt", sep=r"\s+")
print(df) # print(df.head()) to print only the first elements of the dataframe

        _RAJ2000     _DEJ2000     recno        KIC Kepmag  Teff loggF8  \
0    -----------  -----------  --------  ---------  -----  ----  -----   
1    290.9193181  +37.2871547         1    1718958  12.80  6176   3.87   
2    286.6257456  +37.5373047         2    2142522  12.87  6294   3.72   
3    292.4210764  +37.6828081         3    2307415  12.99  6129   3.69   
4    292.9308603  +37.6066408         4    2309719  12.90  6060   3.65   
..           ...          ...       ...        ...    ...   ...    ...   
285  295.5383953  +51.2029639       285   12416661  12.09  6354   3.85   
286  288.0593189  +51.3544539       286   12454461  12.77  6045   3.79   
287  289.0117772  +51.3760244       287   12456063  12.02  6352   4.04   
288  289.7635975  +51.9626142       288   12735740  12.62  5983   3.82   
289  290.4939125  +52.0556111       289   12785320  12.71  5780   3.72   

    loggNEA   RVar r_loggNEA      Simbad        _RA        _DE  
0     -----  -----         -  ----------  ----

In [4]:
# Exporting as CSV
df.to_csv("Bastien-CDS-table.csv", index=False)

In [5]:
teff = df["Teff"]
magnitude = df["Kepmag"]
print(magnitude[1], teff[1])

12.80 6176


In [6]:
type(teff[1])

str

In [7]:
len(teff)

290

In [8]:
teff_ok = np.array([float(teff[x]) for x in range(1, len(teff))])

In [9]:
magnitude_ok = np.array([float(magnitude[i]) for i in range(1, len(magnitude))])

In [10]:
type(teff_ok[1])

numpy.float64

In [11]:
len(teff_ok)

289

In [12]:
print(magnitude_ok[0], teff_ok[0])

12.8 6176.0


## Normalization

In [13]:
# min-max Normalization = x-min/max-min
min_mag = min(magnitude_ok)
max_mag = max(magnitude_ok)
print(f"min={min_mag} max={max_mag}")

magnitude_norm = (magnitude_ok-min_mag)/(max_mag-min_mag)
magnitude_norm

min=8.22 max=13.0


array([0.958159  , 0.97280335, 0.99790795, 0.9790795 , 0.92468619,
       0.91422594, 0.76987448, 0.72594142, 0.9790795 , 0.5041841 ,
       0.84518828, 0.94142259, 0.99790795, 0.67782427, 0.83472803,
       0.96025105, 0.84518828, 0.99790795, 0.48953975, 0.87029289,
       0.35774059, 0.82217573, 0.73012552, 0.        , 0.70292887,
       0.94351464, 0.93305439, 0.99790795, 0.86192469, 0.72175732,
       0.91631799, 0.9790795 , 0.59623431, 0.78033473, 0.53138075,
       0.97698745, 0.94142259, 0.74476987, 0.74058577, 0.69037657,
       0.5251046 , 0.4665272 , 0.87447699, 0.93514644, 0.61506276,
       0.94560669, 0.60251046, 0.85146444, 0.9623431 , 0.93305439,
       0.75313808, 0.69246862, 0.86610879, 0.88284519, 0.89958159,
       0.97698745, 0.43514644, 0.90794979, 0.9707113 , 0.81589958,
       0.5334728 , 0.55439331, 0.75941423, 0.75732218, 0.83054393,
       0.69037657, 0.97698745, 0.65481172, 0.85983264, 0.58577406,
       0.5376569 , 0.9874477 , 0.83054393, 0.67782427, 0.75313

In [14]:
# Rescaling between a set of values, for instance MIDI values [0-127] = a + (x-min)(b-a)/(max-min)
a= 0
b= 127
magnitude_midi = (a + (magnitude_ok-min_mag)*(b-a)/(max_mag-min_mag))
magnitude_midi = magnitude_midi.astype(int) #Converting to float values into integers
magnitude_midi

array([121, 123, 126, 124, 117, 116,  97,  92, 124,  64, 107, 119, 126,
        86, 106, 121, 107, 126,  62, 110,  45, 104,  92,   0,  89, 119,
       118, 126, 109,  91, 116, 124,  75,  99,  67, 124, 119,  94,  94,
        87,  66,  59, 111, 118,  78, 120,  76, 108, 122, 118,  95,  87,
       109, 112, 114, 124,  55, 115, 123, 103,  67,  70,  96,  96, 105,
        87, 124,  83, 109,  74,  68, 125, 105,  86,  95, 115, 115, 123,
       126,  70,  88, 122, 108,  75,  13, 121, 109,  98, 126, 112, 105,
       107,  79,  84, 115, 116, 105, 113,  96, 125,  98, 127, 112, 117,
       123, 117, 100,  67,  51,  89, 123, 126, 115,  49, 120,  86, 126,
        92, 119,  99,  72, 109, 117, 126,  91, 112, 113, 117,  65, 124,
       108,  94,  91, 100, 119,  58, 111,  84, 124, 106,  56,  92, 113,
       119, 123,  60,  99, 109, 123,  78, 115,  39,  98, 125, 104,  91,
       123, 127, 119, 106,  93, 123, 125, 114, 127, 124, 115,  43,  30,
        98,  87, 111,  88, 123, 100, 117, 116, 116, 123, 115,  3

In [15]:
# Mean normalization = x-mean/max-min
mean_mag = np.mean(magnitude_ok)
print(f"mean={mean_mag}")

magnitude_mean_norm = (magnitude_ok-mean_mag)/(max_mag-min_mag)
magnitude_mean_norm

mean=12.064809688581315


array([ 0.1538055 ,  0.16844986,  0.19355446,  0.17472601,  0.1203327 ,
        0.10987245, -0.03447901, -0.07841207,  0.17472601, -0.30016939,
        0.04083479,  0.1370691 ,  0.19355446, -0.12652922,  0.03037454,
        0.15589755,  0.04083479,  0.19355446, -0.31481374,  0.0659394 ,
       -0.44661291,  0.01782224, -0.07422797, -0.80435349, -0.10142462,
        0.13916115,  0.1287009 ,  0.19355446,  0.05757119, -0.08259617,
        0.1119645 ,  0.17472601, -0.20811918, -0.02401876, -0.27297274,
        0.17263396,  0.1370691 , -0.05958362, -0.06376772, -0.11397692,
       -0.27924889, -0.33782629,  0.0701235 ,  0.13079295, -0.18929073,
        0.1412532 , -0.20184303,  0.04711094,  0.1579896 ,  0.1287009 ,
       -0.05121542, -0.11188487,  0.0617553 ,  0.0784917 ,  0.0952281 ,
        0.17263396, -0.36920705,  0.1035963 ,  0.16635781,  0.01154609,
       -0.27088069, -0.24996019, -0.04493927, -0.04703132,  0.02619044,
       -0.11397692,  0.17263396, -0.14954178,  0.05547914, -0.21

In [16]:
# Standardization(Z-score normalization) = x-mean/std

std_mag = np.std(magnitude_ok)
print(f"standard deviation={std_mag}")

magnitude_std_norm = (magnitude_ok-mean_mag)/std_mag
magnitude_std_norm

standard deviation=0.8792242856088549


array([ 0.83618062,  0.91579626,  1.0522802 ,  0.94991725,  0.65420203,
        0.59733372, -0.18744897, -0.42629588,  0.94991725, -1.63190407,
        0.22200287,  0.74519133,  1.0522802 , -0.68789011,  0.16513456,
        0.84755429,  0.22200287,  1.0522802 , -1.7115197 ,  0.35848681,
       -2.42806042,  0.09689258, -0.40354855, -4.37295665, -0.55140616,
        0.75656499,  0.69969668,  1.0522802 ,  0.31299216, -0.4490432 ,
        0.60870738,  0.94991725, -1.13146293, -0.13058066, -1.48404646,
        0.93854358,  0.74519133, -0.32393292, -0.34668024, -0.61964813,
       -1.51816745, -1.83662999,  0.38123414,  0.71107034, -1.02909997,
        0.76793865, -1.09734195,  0.25612385,  0.85892795,  0.69969668,
       -0.27843827, -0.60827447,  0.33573949,  0.42672879,  0.51771808,
        0.93854358, -2.00723492,  0.56321273,  0.9044226 ,  0.0627716 ,
       -1.4726728 , -1.35893618, -0.24431728, -0.25569095,  0.14238723,
       -0.61964813,  0.93854358, -0.81300039,  0.3016185 , -1.18